from xhtml2pdf import pisa
from io import BytesIO
import markdown

def create_styled_pdf(markdown_content, company_name):
    """
    Converts markdown text into a branded Workshop PDF using xhtml2pdf.
    """
    
    # 1. Convert Markdown to HTML
    html_body = markdown.markdown(markdown_content, extensions=['extra'])
    
    # 2. Define HTML Structure & CSS
    # xhtml2pdf uses older CSS standards (no Flexbox), so we use tables for layout.
    
    source_html = f"""
    <html>
    <head>
        <style>
            @page {{
                size: letter;
                margin: 1in;
                @frame footer_frame {{
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 1in;
                    margin-right: 1in;
                    height: 1cm;
                }}
            }}
            body {{
                font-family: Helvetica, Arial, sans-serif;
                font-size: 12px;
                color: #333333;
                background-color: #FDFBF7; /* Workshop Cream */
            }}
            /* Header Table for alignment */
            .header-table {{
                width: 100%;
                border-bottom: 4px solid #F2AAC0; /* Workshop Pink */
                padding-bottom: 10px;
                margin-bottom: 20px;
            }}
            .logo {{
                font-size: 24px;
                font-weight: bold;
                color: #024547; /* Workshop Green */
                text-transform: uppercase;
            }}
            .sub-header {{
                font-size: 10px;
                color: #666;
                text-align: right;
                vertical-align: bottom;
            }}
            
            /* Content Styling */
            h1 {{
                color: #024547;
                font-size: 24px;
                margin-top: 10px;
                text-align: center;
            }}
            h2 {{
                color: #024547;
                font-size: 16px;
                border-bottom: 1px solid #ddd;
                padding-top: 15px;
                padding-bottom: 5px;
                text-transform: uppercase;
            }}
            strong {{
                color: #d1456b; /* Accent Pink/Red */
            }}
            ul {{
                padding-left: 15px;
            }}
            li {{
                margin-bottom: 5px;
                line-height: 1.4;
            }}
            
            /* Footer */
            #footerContent {{
                text-align: center;
                color: #888;
                font-size: 9px;
            }}
        </style>
    </head>
    <body>
        <table class="header-table">
            <tr>
                <td class="logo">Workshop</td>
                <td class="sub-header">ABM STRATEGY GENERATOR</td>
            </tr>
        </table>

        <h1>Strategy for: {company_name}</h1>
        
        {html_body}

        <div id="footerContent">
            Generated by AI Operations • Internal Use Only
        </div>
    </body>
    </html>
    """

    # 3. Render PDF to Memory
    result_file = BytesIO()
    
    # CreatePDF returns a status object
    pisa_status = pisa.CreatePDF(
        source_html,                # the HTML to convert
        dest=result_file            # file handle to receive result
    )
    
    # Check for errors
    if pisa_status.err:
        print(f"PDF generation error: {pisa_status.err}")
        return None
        
    # Rewind the buffer to the beginning so it can be read by Streamlit
    result_file.seek(0)
    
    return result_file
